<?php

namespace App\Http\Controllers\Hub;

use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        $sites = [
            [
                'slug'      => 'desculpometro',
                'emoji'     => '😅',
                'title'     => 'Desculpómetro',
                'desc'      => 'Gera a desculpa perfeita em 1 segundo. Com inteligência artificial, criatividade e zero responsabilidade.',
                'bg'        => '#1a0800',
                'accent'    => '#ff6b00',
                'tag'       => 'TOP',
                'tag_bg'    => '#ff6b00',
                'tag_text'  => '#fff',
                'has_image' => true,
                'n'         => 1,
                'cat'       => 'IA Generativa',
            ],
            [
                'slug'      => 'botao',
                'emoji'     => '🔴',
                'title'     => 'Aperta o Botão',
                'desc'      => 'Um botão. Sem propósito. Sem explicação. Já apertaram mais de um milhão de vezes.',
                'bg'        => '#0a0a0a',
                'accent'    => '#c8f135',
                'tag'       => 'EM ALTA',
                'tag_bg'    => '#c8f135',
                'tag_text'  => '#000',
                'has_image' => true,
                'n'         => 2,
                'cat'       => 'Experiência',
            ],
            [
                'slug'      => 'nomeador',
                'emoji'     => '💬',
                'title'     => 'Nomeador de Grupos',
                'desc'      => 'Chega de grupos chamados "Família 🏠". Gera o nome épico que o teu grupo merece.',
                'bg'        => '#1a0010',
                'accent'    => '#ff2d78',
                'tag'       => null,
                'has_image' => false,
                'n'         => 3,
                'cat'       => 'WhatsApp',
            ],
            [
                'slug'      => 'horoscopo',
                'emoji'     => '🔮',
                'title'     => 'Horóscopo Inútil',
                'desc'      => 'Previsões 100% inventadas, 100% precisas. As estrelas não sabem mais do que isto.',
                'bg'        => '#0d0020',
                'accent'    => '#a855f7',
                'tag'       => null,
                'has_image' => true,
                'n'         => 4,
                'cat'       => 'Pseudo-ciência',
            ],
            [
                'slug'      => 'nome',
                'emoji'     => '🧬',
                'title'     => 'Analisador de Nome',
                'desc'      => 'Descobre o que o teu nome diz sobre ti. Resultados com 73% de confiança científica*.',
                'bg'        => '#001a18',
                'accent'    => '#00d9c0',
                'tag'       => null,
                'has_image' => false,
                'n'         => 5,
                'cat'       => 'IA Generativa',
            ],
            [
                'slug'      => 'bingo',
                'emoji'     => '🎯',
                'title'     => 'Bingo do Imigrante',
                'desc'      => 'Quantas destas situações já te aconteceram em Portugal? A cartela que toda a comunidade BR vai reconhecer.',
                'bg'        => '#1a1500',
                'accent'    => '#ffd600',
                'tag'       => 'PT/BR',
                'tag_bg'    => '#a855f7',
                'tag_text'  => '#fff',
                'has_image' => false,
                'n'         => 6,
                'cat'       => 'Comunidade BR/PT',
            ],
            [
                'slug'      => 'conversor',
                'emoji'     => '🔁',
                'title'     => 'Conversor PT ↔ BR',
                'desc'      => 'Bicha ou fila? Autocarro ou ônibus? O guia definitivo das palavras que nos separam.',
                'bg'        => '#001020',
                'accent'    => '#00aaff',
                'tag'       => 'PT/BR',
                'tag_bg'    => '#a855f7',
                'tag_text'  => '#fff',
                'has_image' => false,
                'n'         => 7,
                'cat'       => 'Língua',
            ],
            [
                'slug'      => 'quiz',
                'emoji'     => '🤔',
                'title'     => 'Sou mais BR ou PT?',
                'desc'      => 'Depois de anos entre os dois países, quanto do outro já absorbeste? 5 perguntas. Resultado imprevisto.',
                'bg'        => '#0a1500',
                'accent'    => '#7bc900',
                'tag'       => 'PT/BR',
                'tag_bg'    => '#a855f7',
                'tag_text'  => '#fff',
                'has_image' => false,
                'n'         => 8,
                'cat'       => 'Quiz',
            ],
            [
                'slug'      => 'corporativo',
                'emoji'     => '💼',
                'title'     => 'Tradutor Corporativo',
                'desc'      => '"Vamos alinhar" = reunião que devia ser email. Traduz o jargão do escritório para português real.',
                'bg'        => '#1a0000',
                'accent'    => '#ff3b3b',
                'tag'       => null,
                'has_image' => false,
                'n'         => 9,
                'cat'       => 'Escritório',
            ],
        ];

        return view('hub.home', compact('sites'));
    }
}
